@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FlashcardAppParser" as FlashcardAppParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "deleteCommand:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> FlashcardAppParser : parseCommand("delete 1")
activate FlashcardAppParser

create DeleteCommandParser
FlashcardAppParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> FlashcardAppParser
deactivate DeleteCommandParser

FlashcardAppParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : deleteCommand
deactivate DeleteCommand

DeleteCommandParser --> FlashcardAppParser : deleteCommand
deactivate DeleteCommandParser

FlashcardAppParser --> LogicManager : deleteCommand
deactivate FlashcardAppParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : deleteFlashcard(1)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand : result
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager:result
deactivate LogicManager
@enduml
