@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FlashCardAppParser" as FlashCardAppParser LOGIC_COLOR
participant ":ListCommandParser" as ListCommandParser LOGIC_COLOR
participant "listCommand:ListCommand" as ListCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "predicate:FlashcardInGivenFlashcardListPredicate" as FlashcardInGivenFlashcardListPredicate MODEL_COLOR
participant ":ModelManager" as ModelManager MODEL_COLOR
end box

[-> LogicManager : execute("list 4")
activate LogicManager

LogicManager -> FlashCardAppParser : parseCommand("list 4")
activate FlashCardAppParser

create ListCommandParser
FlashCardAppParser -> ListCommandParser
activate ListCommandParser

ListCommandParser --> FlashCardAppParser
deactivate ListCommandParser

FlashCardAppParser -> ListCommandParser:parse("4")
activate ListCommandParser

create ListCommand
ListCommandParser -> ListCommand:ListCommand(4)
activate ListCommand

ListCommand --> ListCommandParser : listCommand
deactivate ListCommand

ListCommandParser --> FlashCardAppParser : listCommand
deactivate ListCommandParser
ListCommandParser -[hidden]-> FlashCardAppParser

FlashCardAppParser --> LogicManager : listCommand
deactivate FlashCardAppParser

LogicManager -> ListCommand : execute()
activate ListCommand

create FlashcardInGivenFlashcardListPredicate
ListCommand -> FlashcardInGivenFlashcardListPredicate:
activate FlashcardInGivenFlashcardListPredicate

FlashcardInGivenFlashcardListPredicate --> ListCommand : predicate
deactivate FlashcardInGivenFlashcardListPredicate

ListCommand -> ModelManager : updateFilteredFlashcardList(predicate)
activate ModelManager

ModelManager --> ListCommand
deactivate ModelManager

create CommandResult
ListCommand -> CommandResult
activate CommandResult

CommandResult --> ListCommand : result
deactivate CommandResult

ListCommand --> LogicManager : result
deactivate ListCommand
ListCommand -[hidden]-> LogicManager

[<--LogicManager:result
deactivate LogicManager

@enduml
