@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyFlashcardApp <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface ReadOnlySlideshowApp <<Interface>>
Interface Model <<Interface>>
Class FlashcardApp
Class ReadOnlyFlashcardApp
Class SlideshowApp
Class ReadOnlySlideshowApp
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniqueFlashcardList
Class Flashcard
Class Phrase
Class LanguageType
Class Slideshow

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

FlashcardApp .up.|> ReadOnlyFlashcardApp
SlideshowApp .up.|> ReadOnlySlideshowApp

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyFlashcardApp
Model .left.> ReadOnlySlideshowApp
ModelManager -left-> "1" FlashcardApp
ModelManager -left-> "1" SlideshowApp
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

FlashcardApp *--> "1" UniqueFlashcardList
UniqueFlashcardList --> "~* all" Flashcard
Flashcard *--> "2" Phrase
Flashcard *--> "1" LanguageType

SlideshowApp *--> "1" Slideshow
Slideshow --> "slideshow flashcards ~*" Flashcard

ModelManager -->"~* filtered" Flashcard
@enduml
