@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class SlideshowApp


Package Slideshow <<Rectangle>>{
Class Slideshow
}


Package Flashcard <<Rectangle>>{
Class Flashcard
Class Phrase
}

}

SlideshowApp *--> "1" Slideshow
Slideshow "1" --> "*" Flashcard
Flashcard *--> "3" Phrase

@enduml
