@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
show members
hide methods

skinparam Class {
    AttributeFontColor #FFFFFF
}

Package Model <<Rectangle>>{
    Interface ReadOnlySlideshowApp <<Interface>>
    Class SlideshowApp {
        currentFlashcard: ObjectProperty<Flashcard>
        isActive: BooleanProperty
        isAnswerDisplayed: BooleanProperty
    }
    Class Slideshow
    Class Flashcard
    Class LanguageType
    Class Phrase
}

SlideshowApp .up.|> ReadOnlySlideshowApp
SlideshowApp *--> "1" Slideshow
Slideshow "1" --> "*" Flashcard
Flashcard *--> "1" LanguageType
Flashcard *--> "2" Phrase

@enduml
