@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class CommandHelpMessage
Class ResultDisplay
Class FlashcardListPanel
Class Slideshow
Class FlashcardHeaderBar
Class FlashcardPane
Class StatusBarFooter
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" FlashcardListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow -down-> "0..1" HelpWindow

FlashcardListPanel -down-> "0..1" Slideshow
FlashcardListPanel -down-> "1" FlashcardHeaderBar
FlashcardListPanel -down-> "*" FlashcardPane
HelpWindow <-down-> "*" CommandHelpMessage

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
FlashcardListPanel --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart
CommandHelpMessage --|> UiPart
Slideshow --|> UiPart
FlashcardHeaderBar --|> UiPart
FlashcardPane --|> UiPart

FlashcardPane ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

FlashcardListPanel -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter
StatusBarFooter -[hidden]left- HelpWindow

FlashcardPane -[hidden]left- FlashcardHeaderBar
FlashcardHeaderBar -[hidden]left- Slideshow

MainWindow -[hidden]-|> UiPart
HelpWindow -[hidden]-|> UiPart
@enduml
