@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class CommandHelpMessage
Class CommandBox
Class ResultDisplay
Class FlashcardListPanel
Class FlashcardHeaderBar
Class SlideshowPanel
Class FlashcardPane
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow

MainWindow *-down-> "1" HelpWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" FlashcardListPanel

FlashcardListPanel *-down-> "1" FlashcardHeaderBar
FlashcardListPanel *-down-> "1" SlideshowPanel
FlashcardListPanel *-down-> "*" FlashcardPane
HelpWindow *-down-> "*" CommandHelpMessage

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
FlashcardListPanel --|> UiPart
HelpWindow --|> UiPart
CommandHelpMessage --|> UiPart
SlideshowPanel --|> UiPart
FlashcardHeaderBar --|> UiPart
FlashcardPane --|> UiPart

FlashcardPane ..> Model
SlideshowPanel ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

ResultDisplay -[hidden]left- FlashcardListPanel
CommandBox -[hidden]left- ResultDisplay

@enduml
